.contentPackage: sap-ai-core-llm
.dockerType: default
.workflow: azure-openai-proxy
annotations:
  executables.ai.sap.com/description: OpenAI SM
  executables.ai.sap.com/name: sm-genan-proxy
  scenarios.ai.sap.com/description: OpenAI SM Desc
  scenarios.ai.sap.com/name: sm-genan-scenario
image: docker.io/stojanm/sm-aicore-proxy:1.0
imagePullSecret: de133277-48f8-4919-bdfd-9b1ebe84fafb
labels:
  ai.sap.com/version: '1.0'
  scenarios.ai.sap.com/id: sm-genan-scenario
name: sm-genan-proxy